blank_issues_enabled: false
contact_links:
  - name: 💬 加入 QQ 群交流（1038047655）
    url: https://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=2oA3p4PkON0BqPOQ8YmDfEEEFs3O-Qec&authKey=y7Wh6li8APK%2Bk5s3dkXTrdA%2FSZM1Q8eSIIE%2BlmEXd62YCjdfdQJOhNjnKIWo2%2BSH&noverify=0&group_code=1038047655
    about: 有问题也欢迎加入 QQ 群提问交流，我们乐于帮助你。
