name: ✨ 功能建议
title: '[feat] '
description: 提交你希望 copicseal 添加的新功能或改进
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        谢谢你的建议！我们会认真考虑每一条反馈。

  - type: input
    id: title
    attributes:
      label: 🏷️ 功能名称
      placeholder: 比如：支持批量导出为 WebP 格式
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 功能描述
      placeholder: 请描述这个功能要做什么，它对你有什么帮助？
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 📌 使用场景
      placeholder: 例如，我在处理照片时需要一种更小体积的格式方便分享

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 临时解决方法（如有）
      placeholder: 暂时用 xxx 工具处理后再导入 copicseal

  - type: dropdown
    id: priority
    attributes:
      label: 🚦 你认为这个功能的优先级
      options:
        - 🟢 Nice to have（可以有）
        - 🟡 Important（比较重要）
        - 🔴 Urgent（非常迫切）
